apiVersion: apps/v1
kind: Deloyment
metadata:
  name: deploy-test01
spec:
  replicas: 3
  selector:
    app.kubernetes.io/name: web-deploy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-deploy
    spec:
      containers:
      - name: nginx
        image: nginx:1.24

